import { randomUUID } from "node:crypto";
import { test, expect } from "./quest-fixtures";
import { createQuest, questDay } from "./quest-helpers";

test("Calendar projects Quests and supports timed create, edit and removal in Profile timezone", async ({ page, environment }) => {
  const questTitle = await createQuest(page, "calendar projection");
  await page.getByRole("link", { name: "View today", exact: true }).click();
  const today = await page.getByLabel("Choose date", { exact: true }).inputValue();
  const recurringTitle = `Calendar recurring ${randomUUID()}`;
  const questForm = page.getByRole("region", { name: "Create Quest", exact: true });
  await questForm.getByLabel("Quest type", { exact: true }).selectOption("daily");
  await questForm.getByLabel("Title", { exact: true }).fill(recurringTitle);
  await questForm.getByLabel("Start date", { exact: true }).fill(today);
  await questForm.getByRole("button", { name: "Create recurring Quest", exact: true }).click();
  await expect(questForm.getByRole("status")).toContainText("Recurring Quest created");
  await page.reload(); // Dashboard's existing Quest engine materializes the occurrence.
  await page.getByRole("link", { name: "Calendar", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Calendar", exact: true })).toBeVisible();
  const recurring = page.getByRole("listitem").filter({ has: page.getByRole("heading", { name: recurringTitle, exact: true }) });
  await expect(recurring).toContainText("Recurring Quest");
  await expect(recurring).toContainText("Untimed occurrence");
  await expect(recurring.getByRole("button")).toHaveCount(0);
  await expect(page.getByRole("region", { name: new Date(`${today}T12:00:00Z`).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" }), exact: true })).toContainText("Today");

  await page.goto("/onboarding?repair=timezone");
  await page.getByLabel("Timezone", { exact: true }).selectOption("Asia/Tokyo");
  await page.getByRole("button", { name: "Save profile", exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await page.goto(`/calendar?date=${questDay}&view=day`);
  await expect(page.getByRole("heading", { name: questTitle, exact: true })).toBeVisible();
  const baseline = await environment.sql("SELECT json_build_array((SELECT count(*) FROM public.quest_occurrences),(SELECT count(*) FROM public.quest_events),(SELECT count(*) FROM public.exp_ledger));");
  const title = `Calendar timed ${randomUUID()}`;
  const form = page.getByRole("region", { name: "Create schedule event", exact: true });
  await form.getByLabel("Title", { exact: true }).fill(title);
  await form.getByLabel("Start", { exact: true }).fill(`${questDay}T00:30`);
  await form.getByLabel("End (optional)", { exact: true }).fill(`${questDay}T01:45`);
  await form.getByLabel("Category (optional)", { exact: true }).fill("Class");
  await form.getByLabel("Notes (optional)", { exact: true }).fill("Bring notebook");
  await form.getByRole("button", { name: "Create event", exact: true }).click();
  await expect(form.getByRole("status")).toContainText("Event saved");
  const row = page.getByRole("listitem").filter({ has: page.getByRole("heading", { name: title, exact: true }) });
  await expect(row).toContainText("Schedule event · Class");
  await expect(row).toContainText("Bring notebook");
  expect(await environment.sql(`SELECT (start_at = '2026-09-19T15:30:00Z'::timestamptz)::text FROM public.schedule_events WHERE title='${title}';`)).toBe("true");
  await row.getByRole("button", { name: "Edit", exact: true }).click();
  const edit = page.getByRole("region", { name: "Edit schedule event", exact: true });
  await expect(edit.getByLabel("Start", { exact: true })).toHaveValue(`${questDay}T00:30`);
  await edit.getByLabel("Title", { exact: true }).fill(`${title} edited`);
  await edit.getByLabel("Start", { exact: true }).fill(`${questDay}T02:00`);
  await edit.getByLabel("End (optional)", { exact: true }).fill(`${questDay}T03:00`);
  await edit.getByRole("button", { name: "Save changes", exact: true }).click();
  const edited = page.getByRole("listitem").filter({ has: page.getByRole("heading", { name: `${title} edited`, exact: true }) });
  await expect(edited).toBeVisible();
  await page.reload(); await expect(edited).toBeVisible();
  page.once("dialog", (dialog) => dialog.accept());
  await edited.getByRole("button", { name: "Remove", exact: true }).click();
  await expect(edited).toHaveCount(0);
  expect(await environment.sql("SELECT json_build_array((SELECT count(*) FROM public.quest_occurrences),(SELECT count(*) FROM public.quest_events),(SELECT count(*) FROM public.exp_ledger));")).toBe(baseline);
  await page.goto("/onboarding?repair=timezone");
  await page.getByLabel("Timezone", { exact: true }).selectOption("UTC");
  await page.getByRole("button", { name: "Save profile", exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await page.context().clearCookies();
  await page.goto("/calendar"); await expect(page).toHaveURL(/\/login$/);
});

test("Calendar guards duplicate submits and recovers an accepted create whose response was lost", async ({ page, environment }) => {
  await page.goto(`/calendar?date=${questDay}&view=day`);
  const form = page.getByRole("region", { name: "Create schedule event", exact: true });
  const title = `Calendar recovery ${randomUUID()}`;
  await form.getByLabel("Title", { exact: true }).fill(title);
  await form.getByLabel("Start", { exact: true }).fill(`${questDay}T09:00`);
  let calls = 0;
  let release!: () => void;
  const gate = new Promise<void>((resolve) => { release = resolve; });
  await page.route("**/*", async (route) => {
    if (!route.request().headers()["next-action"]) return route.fallback();
    calls++; await gate; await route.fetch(); await route.abort("failed");
  });
  await form.locator("form").evaluate((element: HTMLFormElement) => { element.requestSubmit(); element.requestSubmit(); });
  await expect(form.getByRole("button", { name: "Saving…", exact: true })).toBeDisabled();
  await expect(form.getByLabel("Title", { exact: true })).toBeDisabled();
  release();
  await expect(form.getByRole("alert")).toContainText("outcome is unknown");
  expect(calls).toBe(1);
  await page.unrouteAll({ behavior: "wait" });
  await form.getByRole("button", { name: "Retry saved request", exact: true }).click();
  await expect(form.getByRole("status")).toContainText("Event saved");
  await expect(page.getByRole("heading", { name: title, exact: true })).toHaveCount(1);
  expect(await environment.sql(`SELECT count(*) FROM public.schedule_events WHERE title='${title}';`)).toBe("1");
});
