// AO L2-02: type-safe feature dictionary, selected by the existing LocaleProvider
// and server-side system-locale cookie. Never translate persisted identifiers.
export const aoCopy = {
  vi: {
    growth: "Phát triển", opportunities: "Cơ hội", activities: "Hoạt động",
    newOpportunity: "Thêm cơ hội", newActivity: "Thêm hoạt động",
    stage: "Giai đoạn theo dõi", outcome: "Kết quả tuyển chọn",
    applicability: "Áp dụng tuyển chọn", participation: "Trạng thái tham gia",
    title: "Tên", organization: "Tổ chức", status: "Trạng thái", detail: "Chi tiết chưa khả dụng",
    archived: "Đã lưu trữ", active: "Đang theo dõi",
    unavailable: "Tính năng đang chờ kiểm thử bảo mật và cơ sở dữ liệu; chưa thể tải hoặc thay đổi bản ghi.",
    notSaved: "Biểu mẫu đang bị khóa. Không có dữ liệu nào được lưu.",
    chooseIntent: "Xác nhận hình thức tham gia thực tế (bắt buộc khi mở chức năng)",
    back: "Quay lại", resource: "Tài nguyên", history: "Lịch sử",
    relationships: "Liên kết", dates: "Thời gian", overview: "Tổng quan", selection: "Tuyển chọn",
    deletedQuest: "Quest đã xóa", more: "Còn kết quả khác",
    confirmedPlan: "Đã xác nhận kế hoạch tham gia",
    confirmedStarted: "Đã xác nhận bắt đầu tham gia",
    historicalCompleted: "Nhập hoạt động đã hoàn thành",
    historicalEndedEarly: "Nhập hoạt động kết thúc sớm",
    filters: "Bộ lọc chưa mở", search: "Tìm theo tên hoặc tổ chức", scope: "Phạm vi",
    searchPlaceholder: "Tìm kiếm khi chức năng được mở",
    unavailableList: "Danh sách chưa được kết nối. Không thể kết luận hiện có hay không có bản ghi.",
    detailPending: "Nội dung chi tiết chỉ hiển thị sau khi kết nối dịch vụ đã được nghiệm thu.",
    disabledPreview: "Các trường dưới đây chỉ minh họa cấu trúc; không thể nhập hay gửi.",
    loading: "Đang xác minh phiên truy cập…", error: "Không thể tải màn hình. Hãy thử lại.", retry: "Thử lại",
    stageLabels: { saved: "Đã lưu", preparing: "Đang chuẩn bị", submitted: "Đã nộp", closed: "Đã đóng" },
    outcomeLabels: { unknown: "Chưa rõ", pending: "Đang chờ", shortlisted: "Vào danh sách ngắn", waitlisted: "Danh sách dự bị", accepted: "Được nhận", rejected: "Không được nhận" },
    applicabilityLabels: { unknown: "Chưa rõ", applicable: "Áp dụng", not_applicable: "Không áp dụng" },
    activityStatusLabels: { upcoming: "Sắp tham gia", ongoing: "Đang tham gia", paused: "Tạm dừng", completed: "Đã hoàn thành", ended_early: "Kết thúc sớm", cancelled_before_start: "Hủy trước khi bắt đầu" },
  },
  en: {
    growth: "Growth", opportunities: "Opportunities", activities: "Activities",
    newOpportunity: "New opportunity", newActivity: "New activity",
    stage: "Tracking stage", outcome: "Selection outcome",
    applicability: "Selection applicability", participation: "Participation status",
    title: "Title", organization: "Organization", status: "Status", detail: "Detail unavailable",
    archived: "Archived", active: "Active",
    unavailable: "This feature is awaiting database and security verification. Records cannot be loaded or changed.",
    notSaved: "This form is disabled. No data has been saved.",
    chooseIntent: "Confirm the actual participation intent (required when enabled)",
    back: "Back", resource: "Resources", history: "History",
    relationships: "Relationships", dates: "Dates", overview: "Overview", selection: "Selection",
    deletedQuest: "Deleted Quest", more: "More results available",
    confirmedPlan: "Confirmed participation plan",
    confirmedStarted: "Confirmed started participation",
    historicalCompleted: "Import completed activity",
    historicalEndedEarly: "Import activity ended early",
    filters: "Filters not yet available", search: "Search title or organization", scope: "Scope",
    searchPlaceholder: "Search when the feature becomes available",
    unavailableList: "The list is not connected. We cannot determine whether any records exist.",
    detailPending: "Details are displayed only after the verified service is connected.",
    disabledPreview: "These fields illustrate the structure only. They cannot be entered or submitted.",
    loading: "Checking your access…", error: "The screen could not be loaded. Please try again.", retry: "Retry",
    stageLabels: { saved: "Saved", preparing: "Preparing", submitted: "Submitted", closed: "Closed" },
    outcomeLabels: { unknown: "Unknown", pending: "Pending", shortlisted: "Shortlisted", waitlisted: "Waitlisted", accepted: "Accepted", rejected: "Rejected" },
    applicabilityLabels: { unknown: "Unknown", applicable: "Applicable", not_applicable: "Not applicable" },
    activityStatusLabels: { upcoming: "Upcoming", ongoing: "Ongoing", paused: "Paused", completed: "Completed", ended_early: "Ended early", cancelled_before_start: "Cancelled before start" },
  },
} as const;
export type AoLocale = keyof typeof aoCopy;
export function aoLanguage(value: unknown): AoLocale { return value === "en" ? "en" : "vi"; }
