import { redirect } from "next/navigation";
import { getProfileContext, isOnboardingComplete } from "@/features/profile/session";
import { ProfileError } from "@/features/profile/profile-error";
import { addCalendarDays, formatCalendarDate, resolveSelectedDate, todayInTimezone } from "@/features/quests/dates";
import { getCalendar } from "@/features/calendar/data";
import { calendarWeek } from "@/features/calendar/model";
import { CalendarPanel } from "@/features/calendar/panel";

export const dynamic = "force-dynamic";
const link = "inline-flex min-h-11 items-center justify-center rounded-md border border-zinc-700 px-3 py-2 text-sm hover:bg-zinc-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white";

export default async function CalendarPage({ searchParams }: { searchParams: Promise<{ date?: string | string[]; view?: string | string[] }> }) {
  const { user, profile, error } = await getProfileContext();
  if (!profile) return <ProfileError missing={error === "missing"} />;
  if (!isOnboardingComplete(profile)) redirect("/onboarding");
  const timezone = profile.timezone!;
  const params = await searchParams;
  const date = resolveSelectedDate(params.date, timezone);
  const today = todayInTimezone(timezone);
  const view = params.view === "day" ? "day" : "week";
  const week = calendarWeek(date);
  const days = view === "day" ? [date] : week;
  const entries = await getCalendar(days[0], days.at(-1)!);
  function adjacent(amount: number) { try { return addCalendarDays(date, amount); } catch { return null; } }
  const previous = adjacent(view === "week" ? -7 : -1), next = adjacent(view === "week" ? 7 : 1);
  const href = (day: string, mode = view) => `/calendar?date=${day}&view=${mode}`;
  return <main className="mx-auto w-full max-w-2xl page-frame">
    <a href="/dashboard" className="inline-flex min-h-11 items-center text-sm text-zinc-400 underline">SYSTEM / Dashboard</a>
    <h1 className="mt-4 text-3xl font-semibold tracking-wide">Calendar</h1>
    <p className="mt-2 text-sm text-zinc-400">Your time, alongside existing Quest occurrences. Timezone: {timezone}.</p>
    <nav aria-label="Calendar navigation" className="mt-6 flex flex-wrap gap-2">
      {previous && <a className={link} href={href(previous)}>Previous {view}</a>}
      <a className={link} href={href(today)}>Today</a>
      {next && <a className={link} href={href(next)}>Next {view}</a>}
      <a className={link} aria-current={view === "day" ? "page" : undefined} href={href(date, "day")}>Day</a>
      <a className={link} aria-current={view === "week" ? "page" : undefined} href={href(date, "week")}>Week</a>
    </nav>
    <form action="/calendar" className="mt-4 flex flex-wrap items-end gap-2">
      <input type="hidden" name="view" value={view} />
      <label className="min-w-0 text-sm">Choose date<input className="mt-1 block min-h-11 max-w-full rounded-md border border-zinc-700 bg-zinc-900 px-3 py-2" name="date" type="date" defaultValue={date} required /></label>
      <button className={link}>View</button>
    </form>
    <nav aria-label="Days of the week" className="mt-4 grid grid-cols-4 gap-2 sm:grid-cols-7">
      {week.map((day) => <a key={day} href={href(day, "day")} aria-label={formatCalendarDate(day)} aria-current={day === date ? "date" : undefined}
        className={`${link} flex-col ${day === today ? "border-sky-500 text-sky-300" : ""} ${day === date ? "bg-zinc-800" : ""}`}>
        <span>{new Intl.DateTimeFormat("en-US", { weekday: "short", timeZone: "UTC" }).format(new Date(`${day}T12:00:00Z`))}</span><span>{Number(day.slice(-2))}</span>
      </a>)}
    </nav>
    <p className="mt-4 text-xs text-zinc-500">Recurring slots appear once generated by the Quest engine. Open Quests to plan or complete work.</p>
    {entries === null ? <section className="mt-6"><p role="alert">Calendar is unavailable right now. Please try again.</p><a className={`${link} mt-3`} href={href(date)}>Retry calendar</a></section>
      : <CalendarPanel key={`${date}:${view}:${timezone}`} entries={entries} days={days} selectedDate={date} today={today} timezone={timezone} userId={user.id} view={view} />}
  </main>;
}
